## Reading in the data

In [173]:
## Import the packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas.tools.plotting import scatter_matrix

import math



In [174]:
anp_df = pd.read_pickle(r'anp.pickle') #feather.read_dataframe('data_science_case/anp.feather')
face_df = pd.read_pickle(r'face.pickle') #feather.read_dataframe('data_science_case/face.feather')
image_df = pd.read_pickle(r'image_data.pickle') #feather.read_dataframe('data_science_case/image_data.feather')
metrics_df = pd.read_pickle(r'image_metrics.pickle') #feather.read_dataframe('data_science_case/image_metrics.feather')
object_labels_df = pd.read_pickle(r'object_labels.pickle') #feather.read_dataframe('data_science_case/object_labels.feather')
survey_df = pd.read_pickle(r'survey.pickle') #feather.read_dataframe('data_science_case/survey.feather')
celebrity_df = pd.read_pickle(r'celebrity.pickle') #feather.read_dataframe('data_science_case/survey.feather')


In [175]:
image_df

image_id  \
0      1316962883971761394_3468175004   
1        552382455733335946_263042348   
2        594552614686078174_263042348   
3        553884883234370621_263042348   
4        725551583154452417_263042348   
5        729007634218530400_263042348   
6        649477932919862696_263042348   
7        528485177494910753_263042348   
8        667774966458266919_263042348   
9        435586528885126653_263042348   
10       434008954413299349_263042348   
11       403618151786657518_263042348   
12       417285336920798479_263042348   
13       441327470883682118_263042348   
14       392696461103773056_263042348   
15       384837154278520209_263042348   
16       395052743169193064_263042348   
17       429765682836845999_263042348   
18       439883129728316622_263042348   
19       392751954312607201_263042348   
20       400998518952866830_263042348   
21       395238596000658851_263042348   
22       797464370532889844_263042348   
23       885055543144920530_263042348   
24      1326419469103248699_263042348   
25       922185875333625364_263042348   
26       816176715270501473_263042348   
27       729283203657152056_263042348   
28      1414821963226728242_263042348   
29      1413389111939389968_263042348   
...                               ...   
41176   1467132874813034559_545497348   
41177   1463457891649678113_545497348   
41178   1458125767732267108_545497348   
41179   1470557832343796710_545497348   
41180   1454458389144239651_545497348   
41181   1494371089445763294_545497348   
41182   1477257421838902908_545497348   
41183   1497360925039471431_545497348   
41184   1469703463775926494_545497348   
41185   1425743483100242642_545497348   
41186   1445787095657582674_545497348   
41187   1417561990351870038_545497348   
41188   1438727142409259779_545497348   
41189   1443682738161896199_545497348   
41190   1417713402369078405_545497348   
41191   1447323194276085366_545497348   
41192   1447468871052290094_545497348   
41193   1403338601198320646_545497348   
41194   1419811308521772206_545497348   
41195   1446588517521194546_545497348   
41196   1401913100756003247_545497348   
41197   1439480237510697970_545497348   
41198   1448869420217810928_545497348   
41199   1409705634303426818_545497348   
41200   1351273293600494118_545497348   
41201   1401668300010137600_545497348   
41202   1334498115662788524_545497348   
41203   1367780159696373409_545497348   
41204   1331397178408802007_545497348   
41205  1323317702517705064_1617538164   

                                     image_link  \
0      https://www.instagram.com/p/BJGysPxgsTy/   
1       https://www.instagram.com/p/eqdOq2JLeK/   
2       https://www.instagram.com/p/hARnP2pLTe/   
3       https://www.instagram.com/p/evy13fpLQ9/   
4       https://www.instagram.com/p/oRrVIcJLfB/   
5       https://www.instagram.com/p/od9JS0JLZg/   
6       https://www.instagram.com/p/kDaL0pJLWo/   
7       https://www.instagram.com/p/dVjngJpLch/   
8       https://www.instagram.com/p/lEactBpLUn/   
9       https://www.instagram.com/p/YLg6PjJLX9/   
10      https://www.instagram.com/p/YF6Ng1JLaV/   
11      https://www.instagram.com/p/WZ8JISJLbu/   
12      https://www.instagram.com/p/XKfs2VJLUP/   
13      https://www.instagram.com/p/Yf6P8bpLdG/   
14      https://www.instagram.com/p/VzI1nMpLWA/   
15      https://www.instagram.com/p/VXN1pVJLWR/   
16      https://www.instagram.com/p/V7gmB4JLRo/   
17      https://www.instagram.com/p/X21ZyOJLWv/   
18      https://www.instagram.com/p/Yax2A6JLTO/   
19      https://www.instagram.com/p/VzVdJRpLXh/   
20      https://www.instagram.com/p/WQogdFpLQO/   
21      https://www.instagram.com/p/V8K2i0JLWj/   
22      https://www.instagram.com/p/sRKZ6upLT0/   
23      https://www.instagram.com/p/xIWVPHpLXS/   
24     https://www.instagram.com/p/BJoY3q_D7U7/   
25      https://www.instagram.com/p/zMQyrsJLYU/   
26      https://www.instagram.com/p/tTpGXzpLRh/   
27      https://www.instagram.com/p/oe7zW2pLY4/   
28     

## Data aggregatie

In [176]:
#####################################
## OBJECTS DATA
#####################################
# df = object_labels_df.groupby("data_amz_label").count().reset_index() ## 2101 possible objects , dit is te veel
# df[df['image_id']>500].reset_index() ## 48 objecten hebben meer dan 500 observaties, laten we 48 kolommen maken
# list_met_columns = df[df['image_id']>500].data_amz_label.tolist() ## een lijst met alle kollommen die we willen
# df = object_labels_df[object_labels_df.data_amz_label.isin(list_met_columns)] ## Filter alle labels die niet vaker voor komen dan 500 keer resulteert in 108k regels


# df = df[['image_id','data_amz_label']] ## selecting only relevant columns (every confidence is >0.7)
# df_object = df.pivot_table(index='image_id', columns='data_amz_label', aggfunc=len, fill_value=0) ## Pivot count (looks like len)
# df_object = df_object.reset_index()
# df_object.head()

In [177]:
f = lambda x: x["image_id"].split("_")[1]  ## Maak functie aan

df = object_labels_df.groupby("data_amz_label").count().reset_index() ## 2101 possible objects , dit is te veel
# df[df['image_id']>500].reset_index() ## 48 objecten hebben meer dan 500 observaties, laten we 48 kolommen maken
list_met_columns = df[df['image_id']>500].data_amz_label.tolist() ## een lijst met alle kollommen die we willen
df = object_labels_df[object_labels_df.data_amz_label.isin(list_met_columns)] ## Filter alle labels die niet vaker voor komen dan 500 keer resulteert in 108k regels

df['user_id']= df.apply(f, axis=1)
df.drop(columns = 'image_id',axis=1,inplace=True)



df = df[['user_id','data_amz_label']] ## selecting only relevant columns (every confidence is >0.7)
df_object = df.pivot_table(index='user_id', columns='data_amz_label', aggfunc=len, fill_value=0) ## Pivot count (looks like len)
df_object = df_object.reset_index()


df_object.set_index('user_id', inplace=True)

df_object = df_object.apply(lambda x: x/x.sum(), axis=1).reset_index()


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [178]:
face_df.head()

image_id  face_id face_gender  face_gender_confidence  \
0  1003944279371027183_703978203      6.0      Female               98.741425   
1  1003944279371027183_703978203      6.0      Female               98.741425   
2  1003944279371027183_703978203      6.0      Female               98.741425   
3  1003944279371027183_703978203     68.0        Male               99.927521   
4  1003944279371027183_703978203     68.0        Male               99.927521   

   face_age_range_high  face_age_range_low  face_sunglasses  face_beard  \
0                 38.0                20.0            False       False   
1                 38.0                20.0            False       False   
2                 38.0                20.0            False       False   
3                 77.0                57.0            False       False   
4                 77.0                57.0            False       False   

   face_beard_confidence  face_mustache  face_mustache_confidence  face_smile  \
0              99.998474          False                 99.999794       False   
1              99.998474          False                 99.999794       False   
2              99.998474          False                 99.999794       False   
3              99.981598          False                 99.993256       False   
4              99.981598          False                 99.993256       False   

   face_smile_confidence  eyeglasses  eyeglasses_confidence   face_emo  \
0              99.916168        True              95.395546        SAD   
1              99.916168        True              95.395546       CALM   
2              99.916168        True              95.395546  SURPRISED   
3              84.395294        True              99.420914      HAPPY   
4              84.395294        True              99.420914        SAD   

   emo_confidence  
0       12.660271  
1        8.252973  
2       24.634266  
3       53.603287  
4        5.509090

In [179]:
#####################################
## FACE --> EMO
#####################################
df = face_df[['image_id','face_id','face_emo','emo_confidence']] ## selecting the emotion's
emo_face =pd.pivot_table(df, index= ['image_id'],columns ='face_emo',values = 'emo_confidence').fillna(0) ## Gemiddelde emotie per foto
emo_face = emo_face.reset_index()
emo_face.head()


#####################################
## FACE --> PEOPLE en GENDER
#####################################
f = lambda x: x["image_id"].split("_")[1]  ## Maak functie aan

df_people_in_pic = face_df[['image_id','face_id']].drop_duplicates()
df_people_in_pic['user_id']= df_people_in_pic.apply(f, axis=1)
df_people_in_pic.drop(columns = 'image_id',axis=1,inplace=True)
df_people_in_pic = df_people_in_pic.drop_duplicates()

df_aantal_people_in_pic = df_people_in_pic.groupby(['user_id']).count().reset_index()
df_aantal_people_in_pic.columns = ['user_id', 'aantal_personen']
df_aantal_people_in_pic


df = face_df[['image_id','face_id','face_gender']].drop_duplicates()
df['user_id']= df.apply(f, axis=1)
df.drop(columns = 'image_id',axis=1,inplace=True)
df = df.drop_duplicates()



df = df[df['face_gender'] == 'Male']  ## Select only males
df = df.groupby('user_id').count().reset_index()
df.columns = ['user_id', 'aantal_mannen', 'mag_weg']
df_aantal_mannen_in_pic = df[['user_id', 'aantal_mannen']]
people = pd.merge(df_aantal_people_in_pic, df_aantal_mannen_in_pic, how='left', on='user_id').fillna(0)
people['aantal_vrouwen'] = people.aantal_personen - people.aantal_mannen 
people['ratio_mannen']  = people.aantal_mannen / people.aantal_personen 
people['ratio_vrouwen']  = people.aantal_vrouwen / people.aantal_personen 

people.head()



#####################################
## FACE --> PEOPLE en GENDER
#####################################
df = face_df[['image_id','face_id','face_age_range_high','face_age_range_low']].drop_duplicates()
df['gem_leeftijd'] = (df.face_age_range_high + df.face_age_range_low ) / 2 
df = df[['image_id','face_id','gem_leeftijd']]

def roundup(x):
    return str(int((x+5)/10)*10) 

df['nearest_decade_leeftijd'] = df.gem_leeftijd.apply(roundup)
df = df[['image_id','face_id','nearest_decade_leeftijd']]
leeftijd_mensen_in_foto = df.pivot_table(index='image_id', columns='nearest_decade_leeftijd', aggfunc=len, fill_value=0) ## Pivot count (looks like len)
leeftijd_mensen_in_foto = leeftijd_mensen_in_foto.reset_index()
leeftijd_mensen_in_foto.columns = ['_'.join(col) for col in leeftijd_mensen_in_foto.columns]
leeftijd_mensen_in_foto.rename(columns={'image_id_': 'image_id'}, inplace=True)
leeftijd_mensen_in_foto.head() 

image_id  face_id_0  face_id_10  face_id_20  \
0   1000126179441391393_30837828          0           2           0   
1   1000135251972767429_31447990          0           0           0   
2  1000159024449036821_265063047          0           0           0   
3  1000185226634350811_276232195          0           0           0   
4  1000204070831242247_143854846          0           0           0   

   face_id_30  face_id_40  face_id_50  face_id_60  face_id_70  face_id_80  
0           3           3           0           0           0           0  
1           1           0           0           0           0           0  
2           2           0           0           0           0           0  
3           0           1           0           0           0           0  
4           1           0           0           0           0           0

In [180]:
people.head()

user_id  aantal_personen  aantal_mannen  aantal_vrouwen  ratio_mannen  \
0  1097967773              100           58.0            42.0      0.580000   
1    11520833               98           61.0            37.0      0.622449   
2  1223036636               17           12.0             5.0      0.705882   
3  1224423305                1            1.0             0.0      1.000000   
4  1249457735               21            6.0            15.0      0.285714   

   ratio_vrouwen  
0       0.420000  
1       0.377551  
2       0.294118  
3       0.000000  
4       0.714286

In [181]:
emo_face.head()

face_emo                       image_id    ANGRY      CALM   CONFUSED  \
0          1000126179441391393_30837828  2.69576  2.688435   1.401609   
1          1000135251972767429_31447990  0.00000  0.000000   0.000000   
2         1000159024449036821_265063047  0.00000  0.000000  13.949105   
3         1000185226634350811_276232195  0.00000  0.000000   4.370034   
4         1000204070831242247_143854846  0.00000  0.000000  10.848862   

face_emo  DISGUSTED      HAPPY        SAD  SURPRISED  
0          0.000000  93.731052   4.116577   4.390028  
1          0.000000  98.248589   0.289029  20.180923  
2          0.000000   5.337354   0.000000  47.158062  
3          6.414753   0.000000   0.000000  24.538427  
4          0.000000  93.676590  26.206802   0.000000

In [182]:
#####################################
## ANP --> ANP
#####################################
# anp_df.anp_label.value_counts() ## 3864 different lengts, laten we enkel pakken met count groter dan 500
df = anp_df[['image_id','anp_label','anp_sentiment']]
df_count = df.groupby("anp_label").count().reset_index() 
list_met_columns = df_count[df_count['image_id']>500].anp_label.tolist() ## een lijst met alle kollommen die we willen (81)

df = df[df.anp_label.isin(list_met_columns)] ## Filter alle labels die niet vaker voor komen dan 500 keer resulteert in 108k regels
anp = df.pivot_table(index='image_id', columns='anp_label', fill_value=0) ## Pivot mean is default
anp = anp.reset_index()
anp.columns = ['_'.join(col) for col in anp.columns]
anp.rename(columns={'image_id_': 'image_id'}, inplace=True)
anp.head()


#####################################
## ANP --> Sentiment
#####################################
# anp_df.emotion_label.value_counts() ## 24 different lengts
df = anp_df[['image_id','emotion_label','emotion_score']]
emotion_score = df.pivot_table(index='image_id', columns='emotion_label', fill_value=0) ## Pivot mean is default
emotion_score = emotion_score.reset_index()
emotion_score.columns = ['_'.join(col) for col in emotion_score.columns]
emotion_score.rename(columns={'image_id_': 'image_id'}, inplace=True)
emotion_score.head()




image_id  emotion_score_acceptance  \
0  1000004599066965477_545497348                       0.0   
1  1000059425592054064_703978203                       0.0   
2   1000065308809420330_46329534                       0.0   
3   1000080765059521113_31736205                       0.0   
4  1000097452173278518_206726006                       0.0   

   emotion_score_admiration  emotion_score_amazement  emotion_score_anger  \
0                       0.0                 0.196933                  0.0   
1                       0.0                 0.346800                  0.0   
2                       0.0                 0.171525                  0.0   
3                       0.0                 0.000000                  0.0   
4                       0.0                 0.198100                  0.0   

   emotion_score_annoyance  emotion_score_anticipation  \
0                   0.0000                         0.0   
1                   0.0000                         0.0   
2                   0.0987                         0.0   
3                   0.0000                         0.0   
4                   0.0000                         0.0   

   emotion_score_apprehension  emotion_score_boredom  emotion_score_disgust  \
0                         0.0                    0.0                    0.0   
1                         0.0                    0.0                    0.0   
2                         0.0                    0.0                    0.0   
3                         0.0                    0.0                    0.0   
4                         0.0                    0.0                    0.0   

   emotion_score_distraction  emotion_score_ecstasy  emotion_score_fear  \
0                        0.0                    0.0                 0.0   
1                        0.0                    0.0                 0.0   
2                        0.0                    0.0                 0.0   
3                        0.0                    0.0                 0.0   
4                        0.0                    0.0                 0.0   

   emotion_score_grief  emotion_score_interest  emotion_score_joy  \
0                  0.0                 0.14640            0.00000   
1                  0.0                 0.09510            0.00000   
2                  0.0                 0.00000            0.00000   
3                  0.0                 0.21045            0.21565   
4                  0.0                 0.00000            0.40130   

   emotion_score_loathing  emotion_score_pensiveness  emotion_score_rage  \
0                     0.0                        0.0                 0.0   
1                     0.0                        0.0                 0.0   
2                     0.0                        0.0                 0.0   
3                     0.0                        0.0                 0.0   
4                     0.0                        0.0                 0.0   

   emotion_score_sadness  emotion_score_serenity  emotion_score_surprise  \
0                0.11260                     0.0                  0.0000   
1                0.11555                     0.0                  0.2026   
2                0.00000                     0.0                  0.0000   
3                0.12340                     0.0                  0.0000   
4                0.09745                     0.0                  0.0000   

   emotion_score_terror  emotion_score_trust  emotion_score_vigilance  
0                   0.0                  0.0                      0.0  
1                   0.0                  0.0                      0.0  
2                   0.0                  0.0                      0.0  
3                   0.0                  0.0                      0.0  
4                   0.0                  0.0                      0.0

In [183]:
anp.head()

image_id  anp_sentiment_bad_hair  \
0   1000065308809420330_46329534                     0.0   
1  1000097452173278518_206726006                     0.0   
2  1000159024449036821_265063047                     0.0   
3  1000185226634350811_276232195                     0.0   
4  1000204070831242247_143854846                     0.0   

   anp_sentiment_bad_sign  anp_sentiment_baked_goods  \
0                     0.0                        0.0   
1                     0.0                        0.0   
2                     0.0                        0.0   
3                     0.0                        0.0   
4                     0.0                        0.0   

   anp_sentiment_beautiful_baby  anp_sentiment_big_glasses  \
0                           0.0                        0.0   
1                           0.0                        0.0   
2                           0.0                        0.0   
3                           0.0                        0.0   
4                           0.0                        0.0   

   anp_sentiment_classic_toy  anp_sentiment_colorful_hair  \
0                        0.0                          0.0   
1                        0.0                          0.0   
2                        0.0                          0.0   
3                        0.0                          0.0   
4                        0.0                          0.0   

   anp_sentiment_comic_life  anp_sentiment_comic_sans  \
0                       0.0                       0.0   
1                       0.0                       0.0   
2                       0.0                       0.0   
3                       0.0                       0.0   
4                       0.0                       0.0   

   anp_sentiment_compact_disc  anp_sentiment_crazy_face  \
0                         0.0                       0.0   
1                         0.0                       0.0   
2                         0.0                       0.0   
3                         0.0                       0.0   
4                         0.0                       0.0   

   anp_sentiment_cute_baby  anp_sentiment_cute_cat  anp_sentiment_cute_couple  \
0                      0.0                    0.57                       0.00   
1                      0.0                    0.00                       0.00   
2                      0.0                    0.00                       0.00   
3                      0.0                    0.00                       0.00   
4                      0.0                    0.00                       0.57   

   anp_sentiment_cute_dog  anp_sentiment_cute_guy  anp_sentiment_cute_kitty  \
0                     0.0                     0.0                       0.0   
1                     0.0                     0.0                       0.0   
2                     0.0                     0.0                       0.0   
3                     0.0                     0.0                       0.0   
4                     0.0                     0.0                       0.0   

   anp_sentiment_dark_chocolate  anp_sentiment_double_exposition  \
0                           0.0                            0.000   
1                           0.0                            0.000   
2                           0.0                            0.000   
3                           0.0                            0.000   
4                           0.0                           -0.013   

   anp_sentiment_double_portrait  anp_sentiment_dyed_hair  \
0                            0.0                      0.0   
1                            0.0                      0.0   
2                            0.0                      0.0   
3                            0.0                      0.0   
4                            0.0                      0.0   

   anp_sentiment_dynamic_light  anp_sentiment_early_days  \
0                          0.0                       0.0   
1                          0.0

In [184]:
#####################################
## IMAGE
#####################################

# image_df.image_id.is_unique ## Image is unique
## DROP COLOMMEN DIE GEEN VOORSPELKRACHT HEBBEN
# image_df.drop(columns = ['image_id','image_link','image_url','user_full_name','user_name', 'user_website','user_profile_pic', 'user_bio'], inplace=True )

##FILTER PLAT SLAAN

# image_df.image_filter.value_counts() ## ongv. 30
df = image_df[['user_id','image_filter']]
# df_count = df.groupby("image_filter").count().reset_index() 
df_filter = df.pivot_table(index='user_id', columns='image_filter', aggfunc= len ,fill_value=0)
df_filter = df_filter.reset_index()
df_filter.columns = [str(col) + '_filter' for col in df_filter.columns]
df_filter.rename(columns={'user_id_filter': 'user_id'}, inplace=True)
## Waar kunnen we gemiddelde van nemen
df_filter.set_index('user_id', inplace=True)
df_filter = df_filter.apply(lambda x: x/x.sum(), axis=1).reset_index()
df_filter.head()
df = image_df[['user_id','image_height','image_width','data_memorability']]

df_mean_vars = df.groupby('user_id').mean().reset_index()


df = image_df[['user_id','user_followed_by','user_follows','user_posted_photos']]
df['aantal_fotos'] = 1 
df_sum_vars = df.groupby('user_id').mean().reset_index() ## Moet ook mean zijn, want haalt niet uit

df_sum_vars.shape  #159
df_mean_vars.shape #159
df_filter.shape #159

temp_df = pd.merge(df_sum_vars, df_mean_vars, how='inner', on='user_id')
image_df_user = pd.merge(temp_df, df_filter, how='inner', on='user_id')
image_df_user.head()



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


user_id  user_followed_by  user_follows  user_posted_photos  \
0  1097967773              53.0         154.0               282.0   
1    11520833             201.0         299.0               312.0   
2  1223036636             169.0         159.0                48.0   
3  1224423305               1.0          18.0                41.0   
4  1249457735              66.0          93.0                30.0   

   aantal_fotos  image_height  image_width  data_memorability  1977_filter  \
0             1    636.730496   632.056738           0.843239      0.00000   
1             1    617.157051   617.166667           0.819178      0.00641   
2             1    640.000000   640.000000           0.869481      0.00000   
3             1    432.365854   593.170732           0.790601      0.00000   
4             1    645.333333   640.000000           0.804556      0.00000   

   Aden_filter  Amaro_filter  Apollo_filter  Ashby_filter  Brannan_filter  \
0     0.063830      0.003546            0.0      0.014184        0.000000   
1     0.000000      0.016026            0.0      0.000000        0.028846   
2     0.000000      0.000000            0.0      0.000000        0.000000   
3     0.000000      0.024390            0.0      0.000000        0.000000   
4     0.033333      0.033333            0.0      0.000000        0.000000   

   Brooklyn_filter  Charmes_filter  Clarendon_filter  Crema_filter  \
0              0.0        0.003546          0.017730      0.007092   
1              0.0        0.000000          0.003205      0.000000   
2              0.0        0.000000          0.000000      0.000000   
3              0.0        0.000000          0.024390      0.000000   
4              0.0        0.000000          0.100000      0.000000   

   Dogpatch_filter  Earlybird_filter  Gingham_filter  Ginza_filter  \
0         0.003546          0.000000        0.074468           0.0   
1         0.000000          0.003205        0.000000           0.0   
2         0.000000          0.000000        0.000000           0.0   
3         0.000000          0.000000        0.000000           0.0   
4         0.000000          0.000000        0.033333           0.0   

   Gotham_filter  Hefe_filter  Helena_filter  Hudson_filter  Inkwell_filter  \
0            0.0     0.014184            0.0       0.003546        0.000000   
1            0.0     0.025641            0.0       0.016026        0.009615   
2            0.0     0.000000            0.0       0.000000        0.000000   
3            0.0     0.000000            0.0       0.000000        0.000000   
4            0.0     0.000000            0.0       0.033333        0.000000   

   Juno_filter  Kelvin_filter  Lark_filter  Lo-fi_filter  Ludwig_filter  \
0     0.024823        0.00000     0.060284      0.003546       0.024823   
1     0.000000        0.00641     0.012821      0.057692       0.012821   
2     0.000000        0.00000     0.000000      0.000000       0.000000   
3     0.000000        0.00000     0.024390      0.000000       0.024390   
4     0.033333        0.00000     0.000000      0.033333       0.000000   

   Maven_filter  Mayfair_filter  Moon_filter  Nashville_filter  Normal_filter  \
0           0.0        0.003546          0.0          0.024823       0.446809   
1           0.0        0.022436          0.0          0.006410       0.599359   
2           0.0        0.000000          0.0          0.000000       0.979167   
3           0.0        0.000000          0.0          0.000000       0.878049   
4           0.0        0.033333          0.1          0.033333       0.233333   

   Perpetua_filter  Poprocket_filter  Reyes_filter  Rise_filter  \
0              0.0               0.0      0.007092     0.003546   
1              0.0               0.0      0.000000     0.025641   
2              0.0               0.0      0.000000     0.000000   
3              0.0               0.0      0.000000     0.000000   
4              0.0               0.0      0.000000     0.000000   

 

In [185]:
#####################################
## Metrix
#####################################
metrics_df['user_id']=metrics_df.apply(f, axis=1)
metrics_df = metrics_df.groupby('image_id').max() ## op een of andere manier werkt drop_duplicates niet vaagg...
metrics_df = metrics_df.reset_index()
df = metrics_df[['user_id','comment_count','like_count']]
metrics_df_user = df.groupby('user_id').mean().reset_index()
metrics_df_user.head()

user_id  comment_count  like_count
0  1097967773       0.731183    5.892473
1    11520833       0.356557    5.540984
2  1223036636       1.978723   11.340426
3  1224423305       0.000000    0.052632
4  1249457735       0.241379    5.689655

In [186]:
#####################################
## IMAGE
#####################################
# survey_df.info()

survey_df.id.is_unique ## Image is unique

True

In [187]:
#####################################
## CELEB
#####################################
# celebrity_df.image_id.is_unique
# celebrity_df.head(20)
# celebrity_df.face_celebrity_name.value_counts() #2177 counts
# GRootste is 20 en gaat heel snel naar 4/5 hier zit geen voorspelende waarde in!

In [188]:
#####################################
## Analyse op aantallen
#####################################

emo_face.shape#(15957, 7)   NIet elke foto heeft mensen erin
df_object.shape#(31051, 48) Niet elke foto heeft een getraind object, gelukkig wel veel gevonden
emotion_score.shape#(41292, 24) Voor paar fotos niet gevuld
leeftijd_mensen_in_foto.shape#(15957, 9)   NIet elke foto heeft mensen erin
# people.shape#(15957, 6)   NIet elke foto heeft mensen erin
metrics_df.shape#(35803, 4) ##RAAR dat dit niet voor elke gevuld is.... Denk dat de data die we hebben gekregen beetje corrupt is, zaten ook duplicates tussen
image_df.shape#(41206, 18) ## dit zijn alle fotos
anp.shape#(22377, 82) ## We hebben hierin gesneden dus dit kan kloppen

(22377, 82)

In [189]:
#####################################
## User id uit elke extracten
#####################################
f = lambda x: x["image_id"].split("_")[1]  ## Maak functie aan

emo_face['user_id'] = emo_face.apply(f, axis=1)
# df_object['user_id'] =df_object.apply(f, axis=1) IS NU AL PLAT GESLAGEN
emotion_score['user_id']= emotion_score.apply(f, axis=1)
leeftijd_mensen_in_foto['user_id']= leeftijd_mensen_in_foto.apply(f, axis=1)
anp['user_id']=anp.apply(f, axis=1)


In [190]:
#####################################
## Aggegreren op user_id
#####################################
emo_user_face =emo_face.loc[:, emo_face.columns != 'image_id'].groupby('user_id').mean().reset_index()
object_user = df_object
# object_user = df_object.loc[:, df_object.columns != 'image_id'].groupby('user_id').sum().reset_index() ## BOVEN AL PLAT GESLAGEN
emo_user =emotion_score.loc[:, emotion_score.columns != 'image_id'].groupby('user_id').mean().reset_index()
leeftijd_mensen_in_foto_user = leeftijd_mensen_in_foto.loc[:, leeftijd_mensen_in_foto.columns != 'image_id'].groupby('user_id').sum().reset_index()
anp_user =anp.loc[:, anp.columns != 'image_id'].groupby('user_id').mean().reset_index()
# people ## deze is al op niveau van user
# image_df_user ## deze is ook al op niveau

In [191]:
part1 = emo_user_face.iloc[:,1:]/100  
part2 = emo_user_face.iloc[:,:1]


In [192]:
emo_user_face = pd.merge(part2, part1, left_index=True, right_index=True)

In [193]:
emo_user['user_id'] = emo_user['user_id'].astype('int64')
object_user['user_id'] = object_user['user_id'].astype('int64')
leeftijd_mensen_in_foto_user['user_id'] = leeftijd_mensen_in_foto_user['user_id'].astype('int64')
anp_user['user_id'] = anp_user['user_id'].astype('int64')
people['user_id'] = people['user_id'].astype('int64')
image_df_user['user_id'] = image_df_user['user_id'].astype('int64')
metrics_df_user['user_id'] = metrics_df_user['user_id'].astype('int64')
emo_user_face['user_id'] = emo_user_face['user_id'].astype('int64')

temp = pd.merge(survey_df, emo_user, how='left', left_on='insta_user_id', right_on='user_id')
temp2 = pd.merge(temp, object_user, how='left', left_on='insta_user_id', right_on='user_id')
temp3 = pd.merge(temp2, leeftijd_mensen_in_foto_user, how='left', left_on='insta_user_id', right_on='user_id')
temp4 = pd.merge(temp3, anp_user, how='left', left_on='insta_user_id', right_on='user_id')
temp5 = pd.merge(temp4, people, how='left', left_on='insta_user_id', right_on='user_id')
temp6 = pd.merge(temp5, image_df_user, how='left', left_on='insta_user_id', right_on='user_id')
temp7 = pd.merge(temp6, metrics_df_user, how='left', left_on='insta_user_id', right_on='user_id')
platte_df = pd.merge(temp7, emo_user_face, how='left', left_on='insta_user_id', right_on='user_id')

platte_df.shape



(161, 282)

In [194]:
## Alle kolommmen bekijken
from IPython.display import display
pd.options.display.max_columns = None
display(platte_df.head())

index                                id  gender  born  \
0      0  920bf027f7d13dbdc7b66b3d3324903c    Male  1975   
1      1  b433b2bfe49e28d0b7c45925b53084e0    Male  1978   
2      4  f4f54676f75f47c17dc434cf68845328  Female  1990   
3      5  a27a5fc47a59f35761705330253a58e3    Male  1997   
4      6  0a1002b2232a4ecbde604462f6d84bf9  Female  1993   

              education            employed              income  A_2  N_1  \
0      College graduate  Employed for wages  $30,000 to $39,999    4    5   
1      College graduate  Employed for wages  $20,000 to $29,999    8    0   
2  High school graduate  Employed for wages  $80,000 to $89,999    7    3   
3  High school graduate  Employed for wages  $20,000 to $29,999    7    5   
4      College graduate           A student  $20,000 to $29,999    7    5   

   P_1  E_1  A_1  H_1  M_1  R_1  M_2  E_2  LON  H_2  P_2  N_2  A_3  N_3  E_3  \
0    5    3    4    5    6    6    5    5    6    5    6    3    3    4    4   
1    9    7    7    8    8    9    8    9    0    9    9    0    8    0    6   
2    8    7    7    7    8    8    8    8    3    8    8    3    8    4    7   
3    7    4    7    6    7    4    6    4    6    8    6    7    3    6    6   
4    7    4    6    7    7    7    6    7    5    6    2    2    8    2    7   

   H_3  R_2  M_3  R_3  P_3  HAP participate  insta_user_id completed  \
0    4    4    4    4    2  3.0         Yes      619868570      true   
1    8    9    8    9    9  9.0         Yes      187920333      true   
2    7    8    7    7    8  7.0         Yes       33420910      true   
3    6    4    7    3    5  6.0         Yes     2143580844      true   
4    6    6    7    5    8  NaN         Yes      263042348      true   

               start_q                end_q  network_id         P         E  \
0  2016-12-05 14:01:26  2016-12-05 14:02:52  124bd2ceb8  4.333333  4.000000   
1  2016-12-05 14:01:52  2016-12-05 14:03:07  2a0f882bcd  9.000000  7.333333   
2  2016-12-05 14:02:42  2016-12-05 14:03:52  f3ff34e4cf  8.000000  7.333333   
3  2016-12-05 14:02:54  2016-12-05 14:04:08  a48e51bacd  6.000000  4.666667   
4  2016-12-05 14:02:36  2016-12-05 14:04:43  aae4bbb89a  5.666667  6.000000   

          R         M         A   PERMA     N_EMO     P_EMO  imagecount  \
0  4.666667  5.000000  3.666667  4.2500  4.000000  4.333333       465.0   
1  9.000000  8.000000  7.666667  8.2500  0.000000  9.000000         6.0   
2  7.666667  7.666667  7.333333  7.5625  3.333333  8.000000       767.0   
3  3.666667  6.666667  5.666667  5.3750  6.000000  6.000000        43.0   
4  6.000000  6.666667  7.000000     NaN  3.000000  5.666667        73.0   

  private_account   user_id_x  emotion_score_acceptance  \
0          public   619868570                  0.000179   
1          public   187920333                  0.000000   
2          public    33420910                  0.001145   
3          public  2143580844                  0.000000   
4          public   263042348                  0.003263   

   emotion_score_admiration  emotion_score_amazement  emotion_score_anger  \
0                  0.000179                 0.165485             0.016453   
1                  0.000000                 0.144367             0.019433   
2                  0.000000                 0.162936             0.023056   
3                  0.000000                 0.150024             0.029102   
4                  0.000000                 0.170270             0.017107   

   emotion_score_annoyance  emotion_score_anticipation  \
0                 0.000179                    0.000432   
1                 0.000000                    0.000000   
2                 0.000129                    0.000000   
3                 0.000000                    0.000000   
4                 0.000000                    0.000000   

   emotion_score_apprehension  emotion_score_boredom  emotion_score_disgust  \
0                    0.000179               0.007084               0.000520   
1             

In [195]:
platte_df.shape

(161, 282)

## Einde data aggregatie

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
print(scaler)
platte_df = platte_df.dropna()

In [ ]:
listoflabels = ['comment_count','user_follows','user_followed_by','user_posted_photos','image_height','image_width', 'data_memorability','face_id_0','face_id_10','face_id_20','face_id_30','face_id_40','face_id_50','face_id_60','face_id_70','face_id_80', 'aantal_fotos']

In [ ]:
platte_df[['comment_count','user_follows','user_followed_by','user_posted_photos','image_height','image_width', 'data_memorability','face_id_0','face_id_10','face_id_20','face_id_30','face_id_40','face_id_50','face_id_60','face_id_70','face_id_80', 'aantal_fotos']]=scaler.fit_transform(platte_df[['comment_count','user_follows','user_followed_by','user_posted_photos','image_height','image_width', 'data_memorability','face_id_0','face_id_10','face_id_20','face_id_30','face_id_40','face_id_50','face_id_60','face_id_70','face_id_80', 'aantal_fotos']])

In [ ]:

#platte_df = platte_df.drop(labels=listoflabels, axis=1)

In [ ]:

platte_df = platte_df.drop(labels='user_id_y', axis=1)
platte_df = platte_df.ix[:,~platte_df.columns.duplicated()]

In [ ]:
platte_df.user_followed_by

## K-Fold

In [ ]:
from sklearn.model_selection import KFold


# create a k fold with 5 splits, with a fixed random state
kf = KFold(n_splits = 5, shuffle = True, random_state = 1)
result = next(kf.split(platte_df), None)

# create train and test pandas dataframe, with the selected distributions
train = platte_df.iloc[result[0]]
test =  platte_df.iloc[result[1]]

print (result[0])
print (result[1])

In [ ]:
#train.iloc[:,35:38] 

In [ ]:
#train.iloc[22:27,47:100] 

In [ ]:
#train.iloc[22:27,47:100] 

## Feature_selection

In [ ]:
# Recursive Feature Elimination
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import RFECV

import matplotlib.pyplot as plt

In [ ]:
def feature_select(Fit_variables, target_variable , n_variables):
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes
    rfe = RFE(model, n_variables)
    rfe = rfe.fit(Fit_variables , target_variable.astype('str'))
    return rfe
        
def find_column_names_for_ranking(dataset, rfe):
    # calculate index of ranking
    rankingIndex = []
    for x in range(len(rfe.ranking_)):
        if rfe.ranking_[x] == 1:
            rankingIndex.append(x)
            
    # find columns        
    return dataset.iloc[: ,rankingIndex].columns

# select features from the variables with as target the P of the PERMA score, and select top 15 variables
rfe = feature_select(train.iloc[:,47:100] , train.iloc[:,36], 15)
# uncomment to see select binary output
#print(rfe.support_)
#print(rfe.ranking_)

# find the corresponding columns of the ranking
ranking = find_column_names_for_ranking(train.iloc[:,47:100], rfe)   
print (ranking)

In [ ]:
# Create the RFE object and compute a cross-validated score.
svc = SVC(kernel="linear")
# The "accuracy" scoring is proportional to the number of correct
# classifications
rfecv = RFECV(estimator=svc, step=1, cv=StratifiedKFold(2),
              scoring='accuracy')

rfecv.fit(train.iloc[:,47:100] , train.iloc[:,36].astype('str'))


# Plot number of features VS. cross-validation scores
plt.figure()
plt.xlabel("Number of features selected")
plt.ylabel("Cross validation score (nb of correct classifications)")
plt.plot(range(1, len(rfecv.grid_scores_) + 1), rfecv.grid_scores_)
plt.show()

print("Optimal number of features : %d" % rfecv.n_features_)

In [ ]:
len(train['P'])


In [ ]:
for train_index, test_index in kf.split(platte_df):
    print("TRAIN:", train_index, "TEST:", test_index)
    # create train and test pandas dataframe, with the selected distributions
    train = platte_df.iloc[train_index]
    test =  platte_df.iloc[test_index]

## Accuracy

In [ ]:
def accuracy(ranking_variables, target):

    clf = LogisticRegression(random_state=0, solver='lbfgs',
                             multi_class='multinomial').fit(ranking_variables, target)
   
    clf.predict(ranking_variables)
    clf.predict_proba(ranking_variables) 
    score = clf.score(ranking_variables, target)
    #print(score)
    return score
    
accuracy(train[ranking], train['P'].astype('str'))

In [ ]:
# calculate accuracy from 1 to all variables selected
def calc_accuracy_variables(target):
    scores = []
    for n_variables in range(1,len(train.iloc[:,47:])+1): 
        if n_variables % 10 == 0:
            print(n_variables)
        rfe = feature_select(train.iloc[:,47:] , target, n_variables)
        ranking = find_column_names_for_ranking(train.iloc[:,47:], rfe)   
    
        score = accuracy(train[ranking], train['P'].astype('str'))
        scores.append(score)
        #if n_variables <= 20:
        #    print(ranking)
        #print (n_variables," variables, score: ",  score)
    return scores

#calc_accuracy_variables(train['P'])       

In [ ]:
t2 = train.iloc[:,47:]

In [ ]:
# BEREKENT VOOR ELKE FOLD, VOOR ELK AANTAL VARIABELEN, VOOR ELKE LETTER DE ACCURACY EN ONTHOUDT DE HOOGSTE PER LETTER PER FOLD
fold = 0
totaldict = {}
for train_index, test_index in kf.split(platte_df):
    if fold < 1:
        #print("TRAIN:", train_index, "TEST:", test_index)
        # create train and test pandas dataframe, with the selected distributions
        train = platte_df.iloc[train_index]
        test =  platte_df.iloc[test_index]
        fold += 1
        print('######### FOLD', fold)
        high = 0.0000001
        highvar = 0
        highestdict = {}
        for letter in 'PERMA':
            scores = calc_accuracy_variables(train[letter])
            print ("PERMA letter: ", letter)
            for x in range(len(scores)):
                if scores[x] > high:
                    high = scores[x]
                    highvar = x+1
                if x % 10 == 0:
                    print ("accuracy ", x+1, " : ", scores[x])
            highestdict[letter] = (high, highvar)
            high = 0.0000001
            highvar = 0
        totaldict[fold] = highestdict
        print(totaldict)


In [ ]:
backup = totaldict
backup

In [ ]:
# AANGEPAST ZODAT HIJ DE TEST ACCURACY UITREKENT IPV DE TRAIN
def calc_accuracy_variables2(target, n_variables):
    rfe = feature_select(train.iloc[:,47:100] , target, n_variables)
    ranking = find_column_names_for_ranking(train.iloc[:,47:100], rfe)  
    #print(test[ranking])
    score = accuracy(test[ranking], test['P'].astype('str'))
    return score

In [ ]:
## CALCULATES THE TEST ACCURACY
fold = 0
for train_index, test_index in kf.split(platte_df):
    train = platte_df.iloc[train_index]
    test =  platte_df.iloc[test_index]
    print(len(test))
    fold += 1
    print('######### FOLD', fold)
    for letter in 'PERMA':
        print(totaldict[fold][letter][1])
        score = calc_accuracy_variables2(train[letter], totaldict[fold][letter][1])
        print ("PERMA letter: ", letter)
        print ("Accuracy train:", totaldict[fold][letter][0])
        print ("Accuracy test:", score)


In [ ]:
train.ix[:,~train.columns.duplicated()]

In [ ]:
train.iloc[:,47:]

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly = PolynomialFeatures(2)
t2 = train.iloc[:,47:]
x = poly.fit_transform(t2)

y = train['P']

In [ ]:
# Instantiate
lg = LinearRegression()

# Fit
lg.fit(x, y)

# Obtain coefficients
lg.coef_

In [ ]:
clf = LogisticRegression(random_state=0, solver='lbfgs',
                             multi_class='multinomial').fit(x, y.astype('str'))
clf.score(x, y.astype('str'))

# Neural network

## 1. Classifier

In [269]:
# can only drop if not yet done in code before, so try else already satiefied
try:
    platte_df = platte_df.dropna() 
except:
    pass
try:
    platte_df = platte_df.drop(labels='user_id_y', axis=1)
except:
    pass
try:
    platte_df = platte_df.ix[:,~platte_df.columns.duplicated()]
except:
    pass

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # This is added back by InteractiveShellApp.init_path()


#### training and test set

In [270]:
X = platte_df.iloc[:,47:]
y = platte_df["P"].astype(('float'))

y = np.asarray(platte_df["P"], dtype="str")
y


array(['4.333333333333333', '9.0', '8.0', '6.0', '10.0',
       '8.333333333333334', '3.3333333333333335', '7.0', '8.0',
       '8.666666666666666', '7.0', '10.0', '6.666666666666667',
       '8.666666666666666', '7.333333333333333', '7.0',
       '5.666666666666667', '4.0', '6.0', '3.0', '7.333333333333333',
       '7.333333333333333', '10.0', '6.333333333333333',
       '6.666666666666667', '6.666666666666667', '8.0', '4.0',
       '4.333333333333333', '7.333333333333333', '6.666666666666667',
       '8.0', '8.0', '5.0', '5.666666666666667', '6.666666666666667',
       '4.666666666666667', '7.666666666666667', '4.666666666666667',
       '8.666666666666666', '7.0', '6.0', '6.666666666666667', '9.0',
       '8.333333333333334', '5.666666666666667', '7.333333333333333',
       '2.6666666666666665', '6.0', '7.666666666666667',
       '4.666666666666667', '6.666666666666667', '6.333333333333333',
       '7.666666666666667', '7.0', '8.333333333333334', '6.0', '7.0',
       '3.0', '1.66666

In [271]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)


#### Scale model on training set

In [272]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

# pply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

#### training the model

In [273]:
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

def create_classifier(hidden_layer_sizes_tuple, max_iterations):
    '''create mlp classifiers with parameters'''
    mlp = MLPClassifier(hidden_layer_sizes=hidden_layer_sizes_tuple, max_iter=max_iterations)
    return mlp

mlp = create_classifier((50,40,30,30,30,30), 10000)

In [274]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(50, 40, 30, 30, 30, 30),
       learning_rate='constant', learning_rate_init=0.001, max_iter=10000,
       momentum=0.9, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

#### predicting

In [275]:
predictions = mlp.predict(X_test)
predictions

array(['4.666666666666667', '6.0', '6.666666666666667',
       '6.666666666666667', '6.666666666666667', '6.666666666666667',
       '7.333333333333333', '6.666666666666667', '8.333333333333334',
       '3.6666666666666665', '6.666666666666667', '3.6666666666666665',
       '7.333333333333333', '6.0', '6.666666666666667',
       '7.333333333333333', '9.333333333333334', '8.0',
       '7.333333333333333', '6.666666666666667', '7.333333333333333',
       '6.666666666666667', '8.0', '3.6666666666666665',
       '5.666666666666667', '8.0', '8.0', '6.666666666666667',
       '4.666666666666667', '5.666666666666667', '6.666666666666667',
       '7.0', '6.666666666666667', '8.0', '6.666666666666667'],
      dtype='<U18')

In [276]:
from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,predictions))

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 1 0 2 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]


In [277]:
print(classification_report(y_test,predictions))

                    precision    recall  f1-score   support

               3.0       0.00      0.00      0.00         1
3.3333333333333335       0.00      0.00      0.00         1
3.6666666666666665       0.00      0.00      0.00         1
 4.333333333333333       0.00      0.00      0.00         1
 4.666666666666667       0.00      0.00      0.00         2
 5.333333333333333       0.00      0.00      0.00         2
 5.666666666666667       0.00      0.00      0.00         0
               6.0       0.00      0.00      0.00         3
 6.333333333333333       0.00      0.00      0.00         3
 6.666666666666667       0.23      0.60      0.33         5
               7.0       0.00      0.00      0.00         2
 7.333333333333333       0.00      0.00      0.00         1
 7.666666666666667       0.00      0.00      0.00         2
               8.0       0.40      0.40      0.40         5
 8.333333333333334       0.00      0.00      0.00         3
 8.666666666666666       0.00      0.00

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


## 2. Regressor

In [278]:
X = platte_df.iloc[:,47:]
y = np.asarray(platte_df["P"], dtype="float64")


In [279]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)


In [280]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

# pply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [304]:
def create_regressor(hidden_layer_sizes_tuple, max_iterations):
    '''create mlp classifiers with parameters'''
    mlp = MLPRegressor(hidden_layer_sizes=hidden_layer_sizes_tuple, max_iter=max_iterations)
    return mlp
mlp = create_regressor((40,50,30), 10000)

In [305]:
mlp.fit(X_train,y_train)

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(40, 50, 30), learning_rate='constant',
       learning_rate_init=0.001, max_iter=10000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [306]:
mlp.predict(X_test)

array([ 6.97912057, 13.89749792,  7.38539904,  8.94529263,  2.58117863,
        2.73655346,  3.42916267,  5.47565008,  7.85893634,  7.32621891,
        7.50982357,  7.01511283,  4.84033391,  7.85419956, 25.51470773,
       10.52257587,  8.01730846,  6.9595208 ,  7.14796363,  7.14762963,
        3.62538833, 11.26791362,  3.16911859,  7.7637203 ,  5.92830581,
        6.08129811,  7.21198368,  4.24195654,  3.75623505,  6.13628294,
        3.88370177,  3.35339519,  5.92988204,  7.75551834,  4.67546302])

In [307]:
mlp.score(X_test, y_test)

-6.887111522375225